#pragma once
#include <Windows.h>

//muss den gleichen inhalt haben, wie der treiber
#define IO_SEND_PROCESSES CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0700, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_SEND_SYSTEMPROCESSES CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0701, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)


typedef struct _KERNEL_PROCESS_INFO
{
	ULONG pidUserModeAntiCheat;
	ULONG pidGame;
	ULONG bReceived;
}KERNEL_PROCESS_INFO, *PKERNEL_PROCESS_INFO;

typedef struct _KERNEL_SYSTEMPROCESSES_INFO
{
	ULONG pidLsass;
	ULONG pidCsrss1;
	ULONG pidCsrss2;
}KERNEL_SYSTEMPROCESS_INFO, *PKERNEL_SYSTEMPROCESS_INFO;

